music_directory    "/mnt/nas/Media/Music"
db_file            "~/.config/mpd/database"
state_file         "~/.config/mpd/state"
playlist_directory "~/.config/mpd/playlists"

bind_to_address "~/.config/mpd/socket"

audio_output {
    type "pulse"
    name "PulseAudio"
}

